<?php

return [
    'content_types' => [
        'page' => '单页面',
        'article' => '文章',
    ],

    'content_statuses' => [
        'draft' => '草稿',
        'pending' => '待审核',
        'published' => '已发布',
        'offline' => '已下线',
        'rejected' => '已驳回',
    ],

    'channel_types' => [
        'list' => '文章栏目',
        'page' => '单页栏目',
        'link' => '外链栏目',
    ],

    'role_scopes' => [
        'platform' => '平台级',
        'site' => '站点级',
    ],

    'super_admin_user_id' => (int) env('CMS_SUPER_ADMIN_USER_ID', 1),

    'permission_modules' => [
        'attachment' => '附件管理',
        'channel' => '栏目管理',
        'content' => '内容管理',
        'database' => '数据库管理',
        'log' => '操作日志',
        'module' => '功能模块',
        'platform' => '平台管理',
        'platform_role' => '平台角色',
        'promo' => '图宣管理',
        'security' => '安护盾',
        'setting' => '站点设置',
        'site' => '站点管理',
        'system' => '系统设置',
        'theme' => '模板管理',
        'user' => '用户管理',
    ],

    'operation_log_action_labels' => [
        'create' => '新增',
        'update' => '更新',
        'delete' => '删除',
        'switch' => '切换',
        'restore' => '恢复',
        'upload' => '上传',
        'publish' => '发布',
        'disable' => '停用',
        'enable' => '启用',
        'login' => '登录',
        'logout' => '退出',
        'setting' => '配置',
        'restore_template' => '还原模板',
        'upload_library' => '上传资源',
        'upload_image' => '上传图片',
        'upload_media' => '上传媒体',
        'bulk_delete' => '批量删除',
        'bulk_restore' => '批量恢复',
        'bulk_publish' => '批量发布',
        'edit_template' => '编辑模板',
        'remove' => '删除',
        'create_site' => '新增站点',
        'update_site' => '更新站点',
        'delete_site' => '删除站点',
        'switch_theme' => '切换主题',
        'save_theme' => '保存模板',
        'update_settings' => '更新设置',
        'update_permissions' => '更新权限',
        'submit_review' => '提交审核',
        'approve_content' => '审核通过',
        'reject_content' => '驳回内容',
        'bulk_approve_content' => '批量审核通过',
        'force_delete' => '彻底删除',
        'empty' => '清空',
        'reorder' => '拖拽排序',
        'replace' => '替换',
        'activate_template' => '启用站点模板',
        'create_site_template' => '新建站点模板',
        'delete_site_template' => '删除站点模板',
        'delete_orphan_site_template' => '删除孤立模板',
        'create_template' => '新建模板文件',
        'delete_template' => '删除模板文件',
        'rollback_template' => '回滚模板',
        'delete_template_snapshot' => '删除模板快照',
        'favorite_template_snapshot' => '收藏模板快照',
        'unfavorite_template_snapshot' => '取消收藏模板快照',
        'upload_theme_asset' => '上传模板资源',
        'replace_theme_asset' => '替换模板资源',
        'delete_theme_asset' => '删除模板资源',
        'create_item' => '新增图宣项',
        'update_item' => '更新图宣项',
        'replace_item_image' => '替换图宣图片',
        'delete_item' => '删除图宣项',
        'enable_item' => '启用图宣项',
        'disable_item' => '停用图宣项',
        'move_item' => '移动图宣项',
        'reorder_items' => '图宣项排序',
        'duplicate_item' => '复制图宣项',
        'add_site_module_binding' => '新增站点模块绑定',
        'update_site_module_binding' => '更新站点模块绑定',
        'remove_site_module_binding' => '移除站点模块绑定',
        'upgrade_static_vendor' => '升级静态资源',
        'clear_cache_view' => '清理视图缓存',
        'clear_cache_config' => '清理配置缓存',
        'clear_cache_route' => '清理路由缓存',
        'clear_cache_app' => '清理应用缓存',
        'clear_cache_all' => '一键清除缓存',
        'bulk_offline' => '批量下线',
        'switch_site_context' => '切换当前站点',
        'mail_test' => '发送测试邮件',
        'submit_ip_block_active' => '留言提交触发 IP 封禁中',
        'submit_ip_rate_limited' => '留言提交触发 IP 限流',
        'submit_phone_block_active' => '留言提交触发手机号封禁中',
        'submit_phone_rate_limited' => '留言提交触发手机号限流',
        'captcha_verify_block_active' => '验证码校验触发封禁中',
        'captcha_verify_rate_limited' => '验证码校验触发限流',
    ],

    'default_platform_role_permissions' => [
        'super_admin' => [
            'database.manage',
            'module.manage',
            'platform.view',
            'site.manage',
            'platform.user.manage',
            'platform.role.manage',
            'system.check.view',
            'system.setting.manage',
            'platform.log.view',
        ],
        'platform_admin' => [
            'database.manage',
            'module.manage',
            'platform.view',
            'site.manage',
            'platform.user.manage',
            'system.check.view',
            'system.setting.manage',
            'platform.log.view',
        ],
    ],

    'default_site_role_permissions' => [
        'site_admin' => [
            'channel.manage',
            'promo.manage',
            'content.manage',
            'content.publish',
            'content.audit',
            'attachment.manage',
            'module.use',
            'theme.use',
            'theme.edit',
            'setting.manage',
            'site.user.manage',
            'log.view',
            'security.view',
        ],
        'editor' => [
            'content.manage',
            'promo.manage',
            'attachment.manage',
        ],
        'reviewer' => [
            'content.manage',
            'content.publish',
            'content.audit',
            'log.view',
            'security.view',
        ],
        'uploader' => [
            'attachment.manage',
        ],
        'template_editor' => [
            'theme.use',
            'theme.edit',
        ],
    ],

    'promo_page_scopes' => [
        'global' => '全站通用',
        'home' => '首页',
        'channel' => '栏目页',
        'detail' => '详情页',
        'page' => '单页面',
    ],

    'promo_display_modes' => [
        'single' => '单图',
        'carousel' => '轮播',
        'floating' => '漂浮图',
    ],

    'system_setting_defaults' => [
        'system.name' => env('APP_NAME', 'School CMS'),
        'system.version' => '1.0.0',
        'admin.logo' => '/logo.jpg',
        'admin.favicon' => '/Favicon.ico',
        'attachment.allowed_extensions' => 'jpg,jpeg,png,gif,webp,pdf,doc,docx,xls,xlsx,ppt,pptx,zip,rar',
        'attachment.max_size_mb' => 10,
        'attachment.image_max_size_mb' => 5,
        'attachment.image_max_width' => 4096,
        'attachment.image_max_height' => 4096,
        'attachment.image_auto_resize' => false,
        'attachment.image_auto_compress' => false,
        'attachment.image_quality' => 82,
        'admin.enabled' => true,
        'admin.disabled_message' => '后台暂时关闭，请联系系统管理员。',
        'security.site_protection_enabled' => true,
        'security.block_bad_path_enabled' => true,
        'security.block_sql_injection_enabled' => true,
        'security.block_xss_enabled' => true,
        'security.block_path_traversal_enabled' => true,
        'security.block_bad_upload_enabled' => true,
        'security.rate_limit_enabled' => true,
        'security.rate_limit_window_seconds' => 10,
        'security.rate_limit_max_requests' => 30,
        'security.rate_limit_sensitive_max_requests' => 10,
        'security.event_retention_limit' => 200,
        'security.stats_retention_days' => 180,
        'mail.enabled' => false,
        'mail.driver' => 'log',
        'mail.host' => '',
        'mail.port' => 465,
        'mail.username' => '',
        'mail.password_encrypted' => '',
        'mail.encryption' => 'ssl',
        'mail.from_address' => '',
        'mail.from_name' => env('APP_NAME', 'School CMS'),
        'mail.reply_to_address' => '',
        'mail.timeout_seconds' => 10,
        'mail.rate_limit_enabled' => true,
        'mail.rate_limit_window_seconds' => 60,
        'mail.rate_limit_global_max' => 20,
        'mail.rate_limit_site_max' => 10,
        'mail.rate_limit_scene_max' => 5,
        'mail.rate_limit_recipient_window_seconds' => 600,
        'mail.rate_limit_recipient_max' => 5,
        'login.service_agreement_content' => "欢迎使用本系统。\n登录前请确认你已阅读并同意本平台服务协议，并承诺合法合规使用系统功能。\n如不同意服务协议内容，请不要继续登录。",
    ],

    'static_vendor_manifest_path' => public_path('vendor/vendor-assets.json'),
    'static_vendor_root_path' => base_path(),
    'static_vendor_version_cache_seconds' => 1800,
];
