<?php

return [
    'limits' => [
        'max_limit' => 100,
        'max_per_page' => 50,
        'max_window' => 5,
        'max_keyword_length' => 50,
    ],

    // Static config access whitelist prefix.
    'config_prefix_whitelist' => [
        'site.',
        'theme.',
        'seo.',
        'system.',
    ],

    // V2 function whitelist (canonical names).
    'functions' => [
        'query',
        'config',
        'linkTo',
        'themeAsset',
        'themeStyle',
        'themeScript',
        'siteValue',
        'contentList',
        'contentPage',
        'channels',
        'channel',
        'children',
        'parent',
        'siblings',
        'breadcrumb',
        'content',
        'promo',
        'promos',
        'truncate',
        'plainText',
        'formatDate',
        'timeAgo',
        'textToHtml',
        'valueOr',
        'first',
        'nav',
        'stats',
        'guestbookStats',
        'guestbookMessages',
        'previous',
        'next',
        'related',
    ],

    // V2 filter whitelist (pipe filters).
    'filters' => [
        'plainText',
        'truncate',
        'default',
        'htmlOut',
        'formatDate',
        'timeAgo',
        'textToHtml',
    ],

    // Canonical query method names for the query-chain DSL.
    'query_methods' => [
        'channel',
        'channelId',
        'type',
        'status',
        'top',
        'featured',
        'hasImage',
        'author',
        'source',
        'includeIds',
        'excludeIds',
        'keyword',
        'publishedBetween',
        'publishedAfter',
        'publishedBefore',
        'orderBy',
        'random',
        'fields',
        'offset',
        'limit',
        'perPage',
        'pageName',
        'window',
        'siteWide',
        'tree',
        'parentId',
        'nav',
        'scope',
        'template',
        'displayMode',
        'previousOf',
        'nextOf',
        'relatedTo',
        'first',
        'get',
        'paginate',
    ],

    // Transitional alias table used during implementation. Not exposed in docs.
    'aliases' => [
        'is_recommend' => 'featured',
        'is_top' => 'top',
        'with_cover' => 'hasImage',
        'has_image' => 'hasImage',
        'channel_slug' => 'channel',
        'channel_id' => 'channelId',
        'include_ids' => 'includeIds',
        'exclude_ids' => 'excludeIds',
        'order_by' => 'orderBy',
    ],
];
